### ISSUE TITLE
Double leters in aplications are being sqezed

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/noosa_council#4]
See for instance https://www.planningalerts.org.au/applications/1124886 - the top of the page correctly says "Noosa heads" but the label lower down says "Shop Fitout - 3 Lanyana Way NOSA HEADS"

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_i6h1)

**Comment by CloCkWeRX** [comment]
e5604109ed52972e95c7020f577ee4d71a255fad should fix it
